### ISSUE TITLE
v0.2.1 is failing heroku build

### ISSUE THREAD

**Issue by waitingallday** [guardian/scribe-plugin-toolbar#19]
Just a quick heads up, heroku's node buildpack doesn't include bower, so attempting to run bower via postinstall will cause it to fail.

```sh: node_modules/bower/bin/bower: No such file or directory```

Should bower be added as a dev dep?

**Comment by b2whats** [comment]
+1 рукожоп блять

**Comment by rrees** [comment]
@waitingallday okay, I'll change it but out of curiosity what are you building on running that involves this plugin and Heroku?

**Comment by rrees** [comment]
@waitingallday I just checked and bower is listed as a devDependency for the package, is there something else happening here?

**Comment by waitingallday** [comment]
@rrees Yeah sorry, let me give you a bit more background detail. We're building a publishing platform, the app is Rails 4 using webpack for asset pipeline, running on heroku with assets hosted on s3. The admin interface was built by an external agency, who used a few of the scribe modules.

We've been trialling Review Apps with heroku, where it spins up an app every time you open a PR, and noticed yesterday they were all failing on a build step - we tracked it back to the npm postinstall that was added in 0.2.1 of this module.

I moved bower out locally to reproduce what we were seeing on heroku (the error above), and from what I can tell the default nodejs buildpack that heroku uses as a system image does not include bower. It's a super edge problem, but I thought you'd like to know! I fixed our process by holding the version at 0.2.0 for now.

**Comment by jackmoore** [comment]
Having the same error just developing locally (and not using Heroku).  It's only with 0.2.1, 0.2.0 installs fine.  Here is the NPM output

```
npm ERR! scribe-plugin-toolbar@0.2.1 postinstall: `node_modules/bower/bin/bower install`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the scribe-plugin-toolbar@0.2.1 postinstall script 'node_modules/bower/bin/bower install'.
npm ERR! This is most likely a problem with the scribe-plugin-toolbar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node_modules/bower/bin/bower install
npm ERR! You can get their info via:
npm ERR!     npm owner ls scribe-plugin-toolbar
npm ERR! There is likely additional logging output above.
```

**Comment by rrees** [comment]
Okay, I'll remove it for now and do a new release, it's really to avoid the situation locally where you run `npm run test` without having updated the Bower dependencies.

**Comment by rrees** [comment]
Could you re-test with v0.2.2?

**Comment by jackmoore** [comment]
v0.2.2 works for me.

**Comment by rrees** [comment]
Thanks for the update

**Comment by waitingallday** [comment]
Sorry only coming back to this now, works for me as well!

:beers:
